require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '15.0'

target 'PlantAppExploration' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'PlantAppExplorationTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'PlantAppExploration-tvOS' do
  # Pods for PlantAppExploration-tvOS

  target 'PlantAppExploration-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
